/**
 * Build-time generator for bundled cross-references (Treasury of Scripture
 * Knowledge, via openbible.info — CC-BY). Fetches the expanded CSV, keeps the
 * top-voted references per verse, and writes compact per-book files
 * assets/xref/<bookNumber>.json  ->  { "chap:verse": ["Ref 1", "Ref 2", ...] }
 * plus the static require map src/data/xrefAssets.ts.
 *
 * Run: node scripts/build-xrefs.mjs
 * Attribution required: cross-reference data © openbible.info, CC-BY.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'https://raw.githubusercontent.com/shandran/openbible/master/cross_references_expanded.csv';
const TOP_PER_VERSE = 10;
const MIN_VOTES = 1;

// Canonical 66-book names (must match src/data/books.ts order).
const NAMES = [
  'Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel',
  '1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Esther','Job','Psalms','Proverbs',
  'Ecclesiastes','Song of Solomon','Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos',
  'Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi','Matthew',
  'Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians',
  'Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter',
  '2 Peter','1 John','2 John','3 John','Jude','Revelation',
];

function toRef(bookNum, chap, start, endChap, endNum) {
  const name = NAMES[bookNum - 1];
  if (!name) return null;
  const e = Math.trunc(Number(endNum));
  if (Number.isFinite(e) && e > 0 && Math.trunc(Number(endChap)) === Number(chap) && e !== Number(start)) {
    return `${name} ${chap}:${start}-${e}`;
  }
  return `${name} ${chap}:${start}`;
}

async function main() {
  console.log('Fetching cross-references (~27 MB)…');
  const res = await fetch(SRC);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const text = await res.text();
  const lines = text.split('\n');

  // from-book -> { "chap:verse": [{ref, votes}] }
  const byBook = new Map();
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (!line) continue;
    const c = line.split(',');
    const votes = Number(c[2]);
    if (!Number.isFinite(votes) || votes < MIN_VOTES) continue;
    const fromBook = Number(c[14]);
    const fromChap = Number(c[4]);
    const fromVerse = Number(c[5]);
    const toBook = Number(c[15]);
    const toChap = Number(c[9]);
    const toStart = Number(c[10]);
    if (!fromBook || !fromChap || !fromVerse || !toBook || !toChap || !toStart) continue;
    const ref = toRef(toBook, toChap, toStart, c[12], c[13]);
    if (!ref) continue;

    if (!byBook.has(fromBook)) byBook.set(fromBook, new Map());
    const verses = byBook.get(fromBook);
    const key = `${fromChap}:${fromVerse}`;
    if (!verses.has(key)) verses.set(key, []);
    verses.get(key).push({ ref, votes });
  }

  const outDir = resolve(ROOT, 'assets/xref');
  await mkdir(outDir, { recursive: true });

  let total = 0;
  for (let n = 1; n <= 66; n++) {
    const verses = byBook.get(n) ?? new Map();
    const obj = {};
    for (const [key, list] of verses) {
      const seen = new Set();
      const top = list
        .sort((a, b) => b.votes - a.votes)
        .filter((x) => (seen.has(x.ref) ? false : (seen.add(x.ref), true)))
        .slice(0, TOP_PER_VERSE)
        .map((x) => x.ref);
      if (top.length) {
        obj[key] = top;
        total += top.length;
      }
    }
    await writeFile(resolve(outDir, `${n}.json`), JSON.stringify(obj));
  }

  const map = ['/* AUTO-GENERATED by scripts/build-xrefs.mjs — do not edit. */',
    '/* Cross-references (Treasury of Scripture Knowledge via openbible.info, CC-BY). */',
    'type Xref = Record<string, string[]>; // "chap:verse" -> references',
    'export const XREF_LOADERS: Record<number, () => Xref> = {'];
  for (let n = 1; n <= 66; n++) map.push(`  ${n}: () => require('../../assets/xref/${n}.json') as Xref,`);
  map.push('};', '');
  await writeFile(resolve(ROOT, 'src/data/xrefAssets.ts'), map.join('\n'));

  console.log(`Wrote cross-references for 66 books, ${total} references total.`);
}

main().catch((e) => { console.error(e); process.exit(1); });
