/**
 * Build-time generator for the bundled offline KJV.
 *
 * Fetches a public-domain KJV (thiagobodruk/bible, canonical 66-book order) and
 * writes one compact JSON per book to assets/bible/kjv/<bookNumber>.json, each
 * shaped as `string[][]` (chapters → verse strings). Also generates
 * src/data/kjvAssets.ts, a static require map so Metro bundles each book and the
 * app lazy-loads one book at a time.
 *
 * Run once (and whenever refreshing the text):  node scripts/build-kjv.mjs
 * The KJV is public domain; only reference/structure logic lives in code.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'https://raw.githubusercontent.com/thiagobodruk/bible/master/json/en_kjv.json';

/** Strip the KJV's {italic} supplied-word braces, keep the words, tidy spaces. */
function clean(text) {
  return String(text)
    .replace(/[{}]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

async function main() {
  console.log('Fetching KJV…');
  const res = await fetch(SRC);
  if (!res.ok) throw new Error(`HTTP ${res.status} fetching KJV`);
  // Source is UTF-8 with a BOM; res.json() handles it.
  const books = await res.json();
  if (!Array.isArray(books) || books.length !== 66) {
    throw new Error(`Expected 66 books, got ${books?.length}`);
  }

  const outDir = resolve(ROOT, 'assets/bible/kjv');
  await mkdir(outDir, { recursive: true });

  let totalVerses = 0;
  for (let i = 0; i < 66; i++) {
    const bookNumber = i + 1;
    const chapters = (books[i].chapters ?? []).map((ch) => ch.map(clean));
    totalVerses += chapters.reduce((a, c) => a + c.length, 0);
    await writeFile(resolve(outDir, `${bookNumber}.json`), JSON.stringify(chapters));
  }

  // Static require map (thunks → lazy per-book load).
  const lines = [];
  lines.push('/* AUTO-GENERATED by scripts/build-kjv.mjs — do not edit by hand. */');
  lines.push('/* Static require map so Metro bundles each KJV book; thunks keep loading lazy. */');
  lines.push('type Book = string[][]; // chapters -> verse strings');
  lines.push('export const KJV_LOADERS: Record<number, () => Book> = {');
  for (let n = 1; n <= 66; n++) {
    lines.push(`  ${n}: () => require('../../assets/bible/kjv/${n}.json') as Book,`);
  }
  lines.push('};');
  lines.push('');
  await writeFile(resolve(ROOT, 'src/data/kjvAssets.ts'), lines.join('\n'));

  console.log(`Wrote 66 books, ${totalVerses} verses to assets/bible/kjv/`);
  console.log('Generated src/data/kjvAssets.ts');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
